### ISSUE TITLE
Anim Transform Mask not working.

### ISSUE THREAD

**Issue by spiraloid** [aresdevo/animaide#16]
I've created a bunch of keys by using G while in play mode and auto keying. 

I activate Anim Transform.   moving the object moves the keys as expected.

bug.  I add the mask and setup the ranges.  all keys still move and the mask is ignored.
bug.   if I deactivate or remove the mask.  Anim Transform will not work again when activated unless I try to add the mask again.

![mask_bug](https://user-images.githubusercontent.com/36362743/65161575-a7aaab00-d9ec-11e9-9383-dd6c05c91afa.gif)

console error:
Traceback (most recent call last):
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animaide-master\magnet.py", line 85, in anim_transform_handlers
    animation_transform(obj, fcurve)
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animaide-master\magnet.py", line 124, in animation_transform
    mask_curve = action.fcurves[0]
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by aresdevo** [comment]
The issue should be solved now. Please download the add-on again and let me know if it work for you.
Thanks for reporting the bug.

**Comment by spiraloid** [comment]
just downloaded and tested.  looks like it's still broken.  I accidently had autokey on when I activated.  


  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animaide-master\magnet.py", line 85, in anim_transform_handlers
    animation_transform(obj, fcurve)
  File "C:\Users\bay\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animaide-master\magnet.py", line 124, in animation_transform
    mask_curve = action.fcurves[0]
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by spiraloid** [comment]
looks like it has  to do with normalize display activation,.

**Comment by aresdevo** [comment]
Hmmm. I could replicate the issue before, but after the previous fix I can't anymore. It is working on my Blender.

Having autokey on should not be a problem. Activating normalize display might give the impression that is not doing what you expect but should just be the way it displays what AnimTrasform does (the way that Normalize shows the effect of AnimTransform can be confusing).

The last error message you posted there is exactly as the one before. That makes me wonder if the new version didn't overwrite all the files when you installed it. Just to be sure, remove Animaide from Blender before installing the new version again.

Try that and let me know if it works.

Thanks

**Comment by aresdevo** [comment]
As I was reworking the tool I realized it was very buggy. I have addressed a lot of issues that animTransform had, so hopefully now works well.

let me know.
